print ('Please enter 5 numbers.')
num1 = float(input())
num2 = float(input())
num3 = float(input())
num4 = float(input())
num5 = float(input())
print ('The average of those numbers is:')
print ((num1 + num2 + num3 + num4 + num5) / 5)